
## Practice 1: Creating Arrays

In [10]:
import numpy as np

a=np.array([1,2,3,4])

**Q1.** Create a 1D array of numbers from 10 to 50 using NumPy.

In [13]:

x=np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**Q2.** Create a 2D array of shape (3, 4) filled with ones.

In [16]:
x=np.ones((3,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**Q3.** Convert the following list to a NumPy array and print its shape:
```python
data = [[3, 5, 1], [6, 7, 9], [8, 4, 2]]
```

In [18]:
data = [ [3,5,1], [6,7,9], [8,4,2]]
y=np.array(data)
print(y.shape)

(3, 3)


In [8]:
%pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 206.0 kB/s eta 0:00:59
   - ------


[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


## Practice 2: Shape & Dimensions

**Q4.** Given an array:
```python
arr = np.array([[1, 2], [3, 4], [5, 6]])
```
- What is the shape and dimension of the array?

In [20]:
arr=np.array([ [1,2], [3,4], [5,6]])
print(arr.ndim)
print(arr.shape)

2
(3, 2)


## Practice 3: Reshaping and Transposing

**Q5.** Reshape the following array into a shape of (3, 3):
```python
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
resh=arr.reshape(3,3)


**Q6.** Transpose the reshaped array and print both.

In [22]:
trans=np.transpose(resh)
print(resh)
print(trans)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


**Q7.** Write a function to reverse this array.
```python
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [ ]:
print(arr[10: :-1])

[]


## Practice 4: Higher Dimensions

**Q8.** Create a 3D NumPy array with shape (2, 3, 4) containing numbers from 1 to 24.

In [31]:
x=np.arange(1,25)
y=x.reshape(2,3,4)

**Q9.** What is the `.ndim` and `.shape` of the array in Q8?

In [32]:
print(y.ndim)
print(y.shape)

3
(2, 3, 4)


## Practice 5: Indexing and Slicing

**Q10.** Create an array from 0 to 9 and extract elements from index 2 to 6.

In [ ]:
x=np.arrange(0,10)
print(x[2,6])

**Q11.** Given a 2D array, retrieve the second row and the third column.

```python
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

In [36]:
arr=np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1,2])

6


## Practice 6: Array Operations

**Q12.** Create two arrays of the same shape and perform element-wise addition, subtraction, and multiplication.

In [37]:
x=np.array([ 10,20,30])
y=np.array([40,50,60])
print(x+y)
print(y-x)
print(y*x)

[50 70 90]
[30 30 30]
[ 400 1000 1800]


**Q13.** Compute the dot product of:
```python
a = np.array([1, 2])
b = np.array([3, 4])
```

In [40]:
a=np.array([1,2])
b=np.array([3,4])
x=np.dot(a,b)
print(x)

11


## Practice 7: Mathematical Functions
**Q14.** Use NumPy to compute the square root, exponential, and logarithm of each element in:
```python
arr = np.array([1, 4, 9, 16])
```

In [41]:
arr= np.array([1, 4, 9, 16])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))

[1. 2. 3. 4.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
[0.         1.38629436 2.19722458 2.77258872]


## Practice 8: Boolean Indexing and Filtering
**Q15.** Create an array of 10 random integers between 1 and 100. Filter out the even numbers.

In [42]:
arr=np.random.randint(1,101,size=10)
even=arr[arr%2==0]
print("even numbers:",even)

even numbers: [52 86 70 76 86 58]
